# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package
permissions:
  contents: read

on:
  push:
    branches: [ "main", "dependencies" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Define the job to run before your matrix job
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-matrix: ${{ steps.get-python-versions-action.outputs.latest-python-versions }}
    steps:
    - uses: snok/latest-python-versions@v1
      id: get-python-versions-action
      with:
        min-version: 3.12
        include-prereleases: true

  build:
    needs: [get-python-versions]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ${{ fromJson(needs.get-python-versions.outputs.python-matrix) }}

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pipenv"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: "Lint with ruff"
      run: python3 -m ruff check .        
    - name: "Lint using mypy"
      run: | 
        mypy .
        mypy aiobmsble --strict
    - name: Test with pytest
      run: pytest
    - name: "Spell checking"
      run: codespell
